<?php if ( !defined( 'ABSPATH' ) ) exit;

/*

	- general
	- global
	- js
	- menu
	- sidebars
	- widgets
	- metaboxes
	- shortcodes
	- breadcrumbs
	- networks
	- networks_path
	- panel

*/

/*===============================================

	T H E M E   O P T I O N S
	Unique options of the theme

===============================================*/

	global
		$st_Options,
		$st_Settings;

	$st_Options = array (
	
		'general'		=>	array (
								'name'				=>	'truemag_',
								'label'				=>	'Truemag',
								'version'			=>	'1.2.3',
								'url'				=>	'http://strictthemes.com/theme/truemag',
								'url-demo'			=>	'http://strictthemes.com/truemag',
								'documentation'		=>	'http://strictthemes.com/documentation',
								'developer'			=>	'StrictThemes',
								'developer-url'		=>	'http://strictthemes.com',
								'stkit-min'			=>	'1.4.1',
								),
		'global'		=>	array (
								'content_width'		=>	849,
								'rss'				=>	true,
								'lang'				=>	true,
								'rtl'				=>	false,
								'excerpt'			=>	25, // words
								'excerpt-in-search'	=>	true,
								'tag-cloud'			=>	13, // px
								'post-formats'		=>	array(
															'enabled'		=>	true,
															'post-title'	=>	true, // metabox option
															'aside'			=>	array(
																						'status'		=>	false,
																						'label'			=>	__( 'Aside', 'strictthemes' ),
																					),
															'image'			=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Image', 'strictthemes' ),
																					),
															'gallery'		=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Gallery', 'strictthemes' ),
																					),
															'audio'			=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Audio', 'strictthemes' ),
																					),
															'video'			=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Video', 'strictthemes' ),
																					),
															'link'			=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Link', 'strictthemes' ),
																					),
															'quote'			=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Quote', 'strictthemes' ),
																					),
															'status'		=>	array(
																						'status'		=>	true,
																						'label'			=>	__( 'Status', 'strictthemes' ),
																					),
															'chat'			=>	array(
																						'status'		=>	false,
																						'label'			=>	__( 'Chat', 'strictthemes' ),
																					),
															),
								'images'			=>	array(
															'thumbnail'		=>	array(
																						'status'		=>	true,
																						'width'			=>	150,
																						'height'		=>	150,
																						'crop'			=>	true,
																						),
															'medium'			=>	array(
																						'status'		=>	true,
																						'width'			=>	300,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															'large'				=>	array(
																						'status'		=>	true,
																						'width'			=>	1030,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															'archive-image'		=>	array(
																						'status'		=>	true,
																						'width'			=>	850,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															'post-image'		=>	array(
																						'status'		=>	true,
																						'width'			=>	679,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															'project-thumb'		=>	array(
																						'status'		=>	true,
																						'width'			=>	262,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															'project-medium'		=>	array(
																						'status'		=>	true,
																						'width'			=>	574,
																						'height'		=>	9999,
																						'crop'			=>	false,
																						),
															),
								'custom-background'	=>	true,
								'custom-header'		=>	false,
								),
		'ctp'			=>	array (
								'post'			=>	'st_project',
								'category'		=>	'st_category',
								'tag'			=>	'st_tag',
								),
		'js'			=>	array (
								'st'			=>	true,
								'menu'			=>	true,
								'theme'			=>	true,
								'prettyPhoto'	=>	true,
								'mediaelement'	=>	true,
								'ie'			=>	true,
								),
		'menu'			=>	array (
								'primary'		=>	true,
								'secondary'		=>	true,
								),
		'sidebars'		=>	array (
								'default'		=>	true,
								'secondary'		=>	true,
								'post-sidebar'	=>	true,
								'homepage'		=>	0,
								'ads'			=>	array(
														__( 'Appears on the header of all pages.', 'strictthemes' ),
														__( 'Appears on the middle of homepage and archives.', 'strictthemes' ),
														__( 'Appears on the bottom of all pages.', 'strictthemes' )
													),
								'projects'		=>	false,
								'footer'		=>	4,
								'bbPress'		=>	true,
								'buddyPress'	=>	true,
								'woocommerce'	=>	true,
								),
		'widgets'		=>	array (
								'sharrre'		=>	true,
								'contact-info'	=>	true,
								'flickr'		=>	true,
								'recent-posts'	=>	true,
								'subscribe'		=>	true,
								),
		'metaboxes'		=>	array (
								'sidebar'		=>	true,
								'post-options'	=>	true,
								),
		'shortcodes'	=>	array (
								'status'		=>	true,
								'column'		=>	true,
								'ul'			=>	true,
								'button'		=>	true,
								'alert'			=>	true,
								'highlight'		=>	true,
								'dropcap'		=>	true,
								'pullquote'		=>	true,
								'toggle'		=>	true,
								'accordion'		=>	true,
								'tabs'			=>	true,
								'googlemap'		=>	true,
								'pricing-table'	=>	true,
								'sidebar'		=>	true,
								'clear'			=>	true,
								'notice'		=>	true,
								'skill'			=>	true,
								'icon-box'		=>	true,
								'gallery'		=>	true,
								),
		'breadcrumbs'	=>	true,
		'font-st'		=>	true,
		'networks'		=>	array (
								'life_RSS',
								'life_Facebook',
								'life_GooglePlus',
								'life_VK',
								//'life_500px',
								'life_Behance',
								'life_Blogger',
								'life_Delicious',
								'life_DeviantART',
								//'life_Digg',
								//'life_Dopplr',
								'life_Dribbble',
								'life_Evernote',
								'life_Flickr',
								'life_Forrst',
								'life_GitHub',
								//'life_Grooveshark',
								'life_Instagram',
								'life_Lastfm',
								'life_LinkedIn',
								//'life_MySpace',
								//'life_Path',
								'life_Picasa',
								'life_Pinterest',
								//'life_Posterous',
								'life_Reddit',
								'life_Skype',
								'life_SoundCloud',
								'life_Spotify',
								'life_Stumbleupon',
								'life_Tumblr',
								'life_Twitter',
								//'life_Viddler',
								'life_Vimeo',
								//'life_Virb',
								'life_WordPress',
								'life_Youtube',
								//'life_Zerply'
								),
		'networks_path'	=>	'18/social/color/',
		'compatibility'	=>	array(
								'yoast'			=>	true,
								'woocommerce'	=>	array(
														'qty'			=>	9,
														'per-row'		=>	3,
														'related'		=>	3,
														'catalog'		=>	array( 250, 250, 1 ),
														'single'		=>	array( 400, 400, 1 ),
														'thumbnail'		=>	array( 150, 150, 1 ),
													),
							),
		'panel'			=>	array(
								'major'			=>	array (
														'status'	=>	true,
														'general'	=>	array(
																			'status'		=>	true,
																			'logo_img'		=>	true,
																			'favicon'		=>	true,
																			'copyrights'	=>	true,
																			'dev_link'		=>	true,
																			'analytics'		=>	true,
																			),
														'blog'		=>	array(
																			'status'		=>	true,
																			'template'		=>	array(
																									'default'			=>	array (
																																'label'			=> __( 'Default', 'strictthemes' ),
																																'status'		=> true,
																																'desc'			=> __( 'This is standard template.', 'strictthemes' ),
																																),
																									't1'				=>	array (
																																'label'			=> '1',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't2'				=>	array (
																																'label'			=> '2',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't3'				=>	array (
																																'label'			=> '3',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't4'				=>	array (
																																'label'			=> '4',
																																'status'		=> true,
																																'desc'			=> __( 'Template with thumbnails.', 'strictthemes' ),
																																),
																									't5'				=>	array (
																																'label'			=> '5',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't6'				=>	array (
																																'label'			=> '6',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't7'				=>	array (
																																'label'			=> '7',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									't8'				=>	array (
																																'label'			=> '8',
																																'status'		=> true,
																																'desc'			=> __( 'Minimalistic template. Also it used on search page.', 'strictthemes' ),
																																),
																									't9'				=>	array (
																																'label'			=> '9',
																																'status'		=> false,
																																'desc'			=> '',
																																),
																									),
																			'featured'		=> array(
																									'sticky-status'		=>	true,
																									'sticky'			=>	false,
																									'not-in-blogroll'	=>	true,
																									'on-frontpage'		=>	true,
																									'on-archives'		=>	true,
																									'on-single'			=>	true,
																									'on-others'			=>	true,
																									'cache'				=>	true,
																									),
																			),
														'post'		=> array(
																			'status'			=>	true,
																			'after_title'		=>	true,
																			'before_post'		=>	true,
																			'post_feat_image'	=>	true,
																			'excerpt'			=>	true,
																			'post_meta'			=>	array(
																										'status'		=>	true,
																										'author_info'	=>	true,
																										'post_views'	=>	true,
																										'nice_time'		=>	true
																										),
																			'after_post'		=>	true,
																			'post_comments'		=>	true,
																			'related'			=>	true,
																			),
														'page'		=> array(
																			'status'			=>	true,
																			'page_comments'		=>	true
																			),
														'sidebar'		=> array(
																			'status'			=>	true,
																			'additional'		=>	true
																			),
														),
								'layout'		=>	array(
														'status'	=> true,
														'general'	=>	array(
																			'status'			=>	true,
																			'layout_type'		=>	true,
																			'layout_design'		=>	true,
																			),
														'header'	=>	array(
																			'status'			=>	false
																			),
														'footer'	=>	array(
																			'status'			=>	true,
																			'scheme'			=>	array(
																										'status'			=>	true,
																										'default'			=>	'5',
																									),
																			),
														'social'	=>	array(
																			'status'			=>	true,
																			),
														),
								'projects'		=>	array (
														'status'	=>	false,
														'general'	=>	array(
																			'status'			=>	false,
																			'slugs'				=>	false,
																			),
														'portfolio'	=>	array(
																			'status'			=>	false,
																			'projects_qty'		=>	false,
																			'templates'			=>	array (
																										'status'		=>	false,
																										'default'		=>	array (
																																'status'		=>	false,
																																'label'			=>	__( 'Default', 'strictthemes' ),
																																'dummy'			=>	false,
																																),
																										't1'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'1',
																																'dummy'			=>	false,
																																),
																										't2'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'2',
																																'dummy'			=>	false,
																																),
																										't3'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'3',
																																'dummy'			=>	false,
																																),
																										't4'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'4',
																																'dummy'			=>	false,
																																),
																										't5'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'5',
																																'dummy'			=>	false,
																																),
																										't6'			=>	array (
																																'status'		=>	false,
																																'label'			=>	'6',
																																'dummy'			=>	false,
																																)
																										),
																			'template-default'	=>	't1',
																			),
														'taxonomy'	=>	array(
																			'status'			=>	false,
																			),
														),
								'fonts'			=>	array(
														'status'	=>	true,
														'general'	=>	array(
																			'status'			=>	true,
																			'font_size'			=>	true,
																			'font_type'			=>	true,
																			'font_custom'		=>	true,
																			),
														),
								'style'			=>	array(
														'status'	=>	true,
														'general'	=>	array(
																			'status'			=>	true,
																			'styles'			=>	array(
																										'status'		=>	true,
																										'light' 		=>	array (
																																'status'		=>	'default',
																																'label'			=>	__( 'Light', 'strictthemes' ),
																																),
																										'dark'			=>	array (
																																'status'		=>	true,
																																'label'			=>	__( 'Dark', 'strictthemes' ),
																																),
																										),
																			'colors'			=>	array(
																										'status'		=>	true,
																										'default'		=>	'',
																										'primary'		=>	array(
																																'hex'			=>	'5b4141',
																																'free'			=>	array(
																																						'@media only screen and ( max-width: 479px ) { body.dark .post-t4 a.post-thumb:after { background: @@; } }',
																																						),
																																'color'			=>	array(
																																						'h1, h2, h3, h4, h5, h6',
																																						'h1 a, h2 a, h3 a, h4 a, h5 a, h6 a',
																																						'a:hover',
																																						'.bbp-body li.bbp-forum-info > a',
																																						'.bbp-body li.bbp-topic-title > a',
																																						'.bbp-body .bbp-meta a:hover',
																																						'.bbp-pagination .bbp-pagination-links span',
																																						'.bbp-pagination .bbp-pagination-links a',
																																						'#buddypress div.activity-meta a:hover',
																																						'#members-list-options .selected',
																																						'#friends-list-options .selected',
																																						'#groups-list-options .selected',
																																						'.status-header > a',
																																						'#page-404 form:before',
																																						'#wp-calendar tbody a',
																																						'.dark #wp-calendar tbody a:hover',
																																						'.tagcloud a span',
																																						'.widget_custom_menu > li > ul > li.current-menu-item > a',
																																						'.nav-next a',
																																						'.nav-previous a',
																																						'#but-prev-next a',
																																						'#wp-pagenavibox .wp-pagenavi *',
																																						'#buddypress div.pagination div.pagination-links *',
																																						'.accordion .toggle-opened .toggle-title',
																																						'.separator-or span',
																																						'.accordion .toggle-opened .toggle-title',
																																						'.separator-or span',
																																						'body.dark #content-parent #article a:hover',
																																						'body.dark #but-prev-next a:hover',
																																						'body.dark #wp-pagenavibox .wp-pagenavi a:hover',
																																						'body.dark #page-404 form input',
																																						'.woocommerce ul.products li.product .price',
																																						'.woocommerce-page ul.products li.product .price',
																																						'.woocommerce .st-woo a.added_to_cart',
																																						'.woocommerce-page .st-woo a.added_to_cart',
																																						'.widget_products ins',
																																						'.widget_product_search #s',
																																						'.widget_recently_viewed_products ins',
																																						'.widget_top_rated_products ins',
																																						'.woocommerce .cart-collaterals .cart_totals table th',
																																						'.woocommerce-page .cart-collaterals .cart_totals table th',
																																						'.woocommerce .cart-collaterals .cart_totals table td',
																																						'.woocommerce-page .cart-collaterals .cart_totals table td',
																																						'.woocommerce .woocommerce-pagination ul.page-numbers li *',
																																						'.woocommerce-page .woocommerce-pagination ul.page-numbers li *',
																																						'.woocommerce .woocommerce-pagination ul.page-numbers li a:hover',
																																						'.woocommerce-page .woocommerce-pagination ul.page-numbers li a:hover',
																																						'.dark.woocommerce #content-parent .woocommerce-pagination ul.page-numbers li a:hover',
																																						'.dark.woocommerce-page #content-parent .woocommerce-pagination ul.page-numbers li a:hover',
																																						),
																																'background-color'	=>	array(
																																						'body.dark', // needed
																																						'caption',
																																						'th',
																																						'#footer',
																																						'.more-link:hover',
																																						'#layout .mejs-controls',
																																						'#buddypress div.item-list-tabs ul li.selected a span',
																																						'#buddypress div.item-list-tabs ul li.current a span',
																																						'#buddypress div.item-list-tabs ul li a span',
																																						'#buddypress div.item-list-tabs ul li a:hover span',
																																						'#buddypress .activity-list li.loading a',
																																						'#buddypress div.activity-meta a:hover span',
																																						'#buddypress #reply-title small a a:hover span',
																																						'#menu',
																																						'ul.menu-2 ul li',
																																						'input[type="button"]:hover',
																																						'.single-author-info-links span:before',
																																						'.st-format-quote-holder > div',
																																						'.status-header-upic',
																																						'.status-content',
																																						'.tagcloud a',
																																						'.sidebar .widget_nav_menu',
																																						'#sidebar .widget-posts',
																																						'#sidebar-secondary .widget-posts-icon',
																																						'.toggle-opened .toggle-title span',
																																						'.accordion .toggle-opened .toggle-title span',
																																						'.pricing-table-gray .pricing-table-title',
																																						'.pricing-table-gray .pricing-table-price',
																																						'.pricing-table-gray .button',
																																						'.pricing-table-dark .pricing-table-title',
																																						'.pricing-table-dark .pricing-table-price',
																																						'.pricing-table-dark .button',
																																						'.notice',
																																						'#post-excerpt',
																																						'body.dark input',
																																						'body.dark select',
																																						'body.dark textarea',
																																						'body.dark .avatar-box',
																																						'body.dark .tagcloud a:hover',
																																						'body.dark .single-author-upic',
																																						'body.dark .post-t4',
																																						'body.dark #posts-t4 .post-t4-no-thumb h3',
																																						'body.dark .posts-highlighted',
																																						'body.dark .posts-related-wrapper div.posts-related-post-wrapper',
																																						'.dark.woocommerce ul.products li.product',
																																						'.dark .st-woo-hover',
																																						'.dark .woocommerce .cart-collaterals .cross-sells ul.products li',
																																						'.dark .woocommerce-page .cart-collaterals .cross-sells ul.products li',
																																						'.woocommerce .widget_layered_nav_filters ul li a',
																																						'.woocommerce-page .widget_layered_nav_filters ul li a',
																																						),
																																'border-top'	=>	array(
																																						'ul.menu-2 ul li:first-child',
																																						),
																																'border-right'	=>	array(
																																						'#buddypress div.item-list-tabs ul li a span:after',
																																						'#buddypress a.bp-primary-action:hover span:before',
																																						'#buddypress #reply-title small a:hover span:before',
																																						),
																																'border-bottom'	=>	array(
																																						'ul.menu-2 ul',
																																						'ul.menu-2 > li > ul > li:first-child > a:before',
																																						'body.dark #posts-t4 .post-t4-no-thumb h3',
																																						'.dark .st-woo-hover',
																																						),
																																),
																										'primary-alt-a'	=>	array(
																																'steps'			=>	'120',
																																'free'			=>	array(
																																						),
																																'color'			=>	array(
																																						),
																																),
																										'secondary'		=>	array(
																																'hex'			=>	'fb9351',
																																'free'			=>	array(
																																						'@media only screen and ( min-width: 960px ) and ( max-width: 1319px ) { .sidebar-secondary-available .post-t4 a.post-thumb:hover:after { background: @@; } }',
																																						'.widget_custom_menu > li > a { box-shadow: 0 0 0 @@ inset, 0 0 0 rgba(0,0,0,0.05) inset; }',
																																						'.widget_custom_menu > li > a:hover, .widget_custom_menu > li.wHover { box-shadow: 7px 0 0 @@ inset, 320px 0 0 rgba(0,0,0,0.05) inset; }',
																																						'.widget_custom_menu > li.current-menu-item > a { box-shadow: 7px 0 0 @@ inset; }',
																																						'.woocommerce a.add_to_cart_button, .woocommerce a.product_type_external { background: none; }',
																																						),
																																'color'			=>	array(
																																						'h1 a:hover, h2 a:hover, h3 a:hover, h4 a:hover, h5 a:hover, h6 a:hover',
																																						'.title-sub',
																																						'a',
																																						'blockquote:before',
																																						'#search-form-header.search-form-header span:before',
																																						'#search-form-header input',
																																						'.bbp-body li.bbp-forum-info > a:hover',
																																						'.bbp-body li.bbp-topic-title > a:hover',
																																						'#subscription-toggle a:before',
																																						'#favorite-toggle a:before',
																																						'.widget_display_stats dd',
																																						'#bbp-search-form > div:before',
																																						'ul.menu li.hasUl > a:before',
																																						'#menu-responsive > li > ul > li > a:before',
																																						'ul.menu-2 > li > a:hover',
																																						'ul.menu-2 > li.hover-has-ul > a',
																																						'ul.menu-2 > li > a:hover:before',
																																						'ul.menu-2 > li.hover-has-ul > a:before',
																																						'ul.menu-2 ul li.hasUl > a:before',
																																						'ul.menu-2 ul li:hover > a',
																																						'.term-title h1:before',
																																						'.meta .ico16:hover:before',
																																						'.widget_search form > div:before',
																																						'#prev a:hover:before',
																																						'#next a:hover:after',
																																						'.widget_custom_menu > li > span:before',
																																						'.widget_custom_menu > li > ul > li > a:before',
																																						'.widget_custom_menu ul ul li a:hover',
																																						'.widget-info p.widget-info-address:before',
																																						'.widget-info p.widget-info-phone:before',
																																						'.widget-info p.widget-info-email:before',
																																						'.widget-info p.widget-info-name:before',
																																						'.sidebar-footer .widget-info p a.mailto',
																																						'#sidebar .widget-posts-most-viewed .widget-posts-icon:hover:before',
																																						'.sidebar-footer .widget-posts-most-viewed .widget-posts-icon:hover:before',
																																						'.widget-subscribe form > div:before',
																																						'.icons-social a:hover',
																																						'.st-ul li.st-current',
																																						'.st-ul li.st-current:hover',
																																						'.st_icon_box:before',
																																						'.woocommerce a.add_to_cart_button:before',
																																						'.woocommerce a.product_type_external:before',
																																						'.woocommerce .star-rating span:before',
																																						'.woocommerce-page .star-rating span:before',
																																						'.widget_product_search label:before',
																																						'.woocommerce .woocommerce-error:before',
																																						'.woocommerce .woocommerce-info:before',
																																						'.woocommerce .woocommerce-message:before',
																																						'.woocommerce-page .woocommerce-error:before',
																																						'.woocommerce-page .woocommerce-info:before',
																																						'.woocommerce-page .woocommerce-message:before',
																																						'body.dark #content-parent h1 a:hover',
																																						'body.dark #content-parent h2 a:hover',
																																						'body.dark #content-parent h3 a:hover',
																																						'body.dark #content-parent h4 a:hover',
																																						'body.dark #content-parent h5 a:hover',
																																						'body.dark #content-parent h6 a:hover',
																																						'body.dark .posts-related-details-wrapper > div h5 a:hover',
																																						'body.dark #page-404 form:before',
																																						'#content-parent .widget_custom_menu > li > ul > li > a:hover',
																																						'.widget_custom_menu > li > ul > li.current-menu-item > a',
																																						'.woocommerce ul.products li.product h3 mark',
																																						'.woocommerce-page ul.products li.product h3 mark',
																																						),
																																'background-color'	=>	array(
																																						'#header-holder-2',
																																						'#copyrights-holder',
																																						'.more-link',
																																						'#layout .mejs-time-loaded',
																																						'.sidebar .widget.widget_display_search',
																																						'.bbp-topic-pagination a',
																																						'#buddypress input[type="submit"]',
																																						'#buddypress input[type="button"]',
																																						'#buddypress input[type="reset"]',
																																						'#buddypress button.submit',
																																						'#buddypress input[type="submit"]:hover',
																																						'#buddypress input[type="button"]:hover',
																																						'#buddypress input[type="reset"]:hover',
																																						'#buddypress button.submit:hover',
																																						'#buddypress div.item-list-tabs ul li.selected a',
																																						'#buddypress div.item-list-tabs ul li.current a',
																																						'#buddypress div#subnav.item-list-tabs ul li.selected a',
																																						'#buddypress div#subnav.item-list-tabs ul li.current a',
																																						'#buddypress .activity-list li.load-more a',
																																						'#menu-select.resp-menu-opened',
																																						'#menu-responsive li a:focus',
																																						'input[type="button"]',
																																						'input[type="submit"]',
																																						'button',
																																						'body.dark input[type="submit"]',
																																						'body.dark button',
																																						'.single-author-info-links span:hover:before',
																																						'.st-format-link',
																																						'.posts-featured-wrapper a.post-thumb:before',
																																						'#sidebar .widget_search',
																																						'.tagcloud a:hover',
																																						'#sidebar .widget-posts-most-viewed',
																																						'#sidebar .widget-posts-icon:hover',
																																						'.sidebar-footer .widget-posts-icon:hover',
																																						'#sidebar-secondary .widget-posts-icon:hover',
																																						'#sidebar .sharrre .count',
																																						'.button-st',
																																						'.dropcap',
																																						'.pricing-table-featured .pricing-table-title',
																																						'.pricing-table-featured .pricing-table-price',
																																						'.pricing-table-featured .button',
																																						'.skill-bar',
																																						'.woocommerce #content input.button',
																																						'.woocommerce #respond input#submit',
																																						'.woocommerce a.button',
																																						'.woocommerce button.button',
																																						'.woocommerce input.button',
																																						'.woocommerce-page #content input.button',
																																						'.woocommerce-page #respond input#submit',
																																						'.woocommerce-page a.button',
																																						'.woocommerce-page button.button',
																																						'.woocommerce-page input.button',
																																						'.woocommerce #content input.button:hover',
																																						'.woocommerce #respond input#submit:hover',
																																						'.woocommerce a.button:hover',
																																						'.woocommerce button.button:hover',
																																						'.woocommerce input.button:hover',
																																						'.woocommerce-page #content input.button:hover',
																																						'.woocommerce-page #respond input#submit:hover',
																																						'.woocommerce-page a.button:hover',
																																						'.woocommerce-page button.button:hover',
																																						'.woocommerce-page input.button:hover',
																																						'.woocommerce #content input.button.alt',
																																						'.woocommerce #respond input#submit.alt',
																																						'.woocommerce a.button.alt',
																																						'.woocommerce button.button.alt',
																																						'.woocommerce input.button.alt',
																																						'.woocommerce-page #content input.button.alt',
																																						'.woocommerce-page #respond input#submit.alt',
																																						'.woocommerce-page a.button.alt',
																																						'.woocommerce-page button.button.alt',
																																						'.woocommerce-page input.button.alt',
																																						'.woocommerce #content input.button.alt:hover',
																																						'.woocommerce #respond input#submit.alt:hover',
																																						'.woocommerce a.button.alt:hover',
																																						'.woocommerce button.button.alt:hover',
																																						'.woocommerce input.button.alt:hover',
																																						'.woocommerce-page #content input.button.alt:hover',
																																						'.woocommerce-page #respond input#submit.alt:hover',
																																						'.woocommerce-page a.button.alt:hover',
																																						'.woocommerce-page button.button.alt:hover',
																																						'.woocommerce-page input.button.alt:hover',
																																						'.woocommerce .widget_price_filter .ui-slider .ui-slider-range',
																																						'.woocommerce-page .widget_price_filter .ui-slider .ui-slider-range',
																																						'.sidebar .widget_product_search',
																																						'body.dark .tagcloud a',
																																						'body.dark .sharrre .count',
																																						),
																																'border-top'	=>	array(
																																						'ul.menu > li > a:hover',
																																						'ul.menu > li.hover-has-ul > a',
																																						'#menu-select.resp-menu-opened',
																																						'.st-ul li.st-current',
																																						'.st-ul li.st-current:hover',
																																						'body.dark .sharrre .count:before',
																																						'.woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
																																						'.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle',
																																						),
																																'border-right'	=>	array(
																																						'#menu-select.resp-menu-opened',
																																						'.woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
																																						'.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle',
																																						),
																																'border-bottom'	=>	array(
																																						'#buddypress div#subnav',
																																						'#menu-select.resp-menu-opened',
																																						'.woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
																																						'.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle',
																																						),
																																'border-left'	=>	array(
																																						'blockquote',
																																						'#menu-select.resp-menu-opened',
																																						'.woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
																																						'.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle',
																																						),
																																),
																										),
																			'background-image'	=>	'',
																			'responsive'		=>	true,
																			),
														'custom'	=>	array(
																			'status'			=>	true,
																			),
														),
								'misc'			=>	array(
														'status'	=>	true,
														'general'	=>	array(
																			'status'		=>	true,
																			),
														'admin_bar'	=>	true,
														'hidpi'		=>	true,
														'redirect'	=>	true,
														'stickymenu'=>	true,
														'sidebar-alt'=>	false,
														'adsense'	=>	true,
														'woocommerce'=>	array(
																			'status'		=>	true,
																			'qty'			=>	true,
																			'assets'		=>	true,
																			),
														),
								'import'		=>	array(
														'status'	=>	true,
														),
								'update'		=>	array(
														'status'	=>	false,
														'general'	=>	array(
																			'status'		=>	true,
																			'source'		=>	'themeforest',
																			),
														),
								),
	); // $st_Options

?>